[package]
name = "charts-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fontdue = "0.7.3"
once_cell = "1.18.0"
snafu = "0.7.4"
substring = "1.4.5"
charts_rs_derive = { path = "./charts_rs_derive"}

[dev-dependencies]
pretty_assertions = "1.3.0"
