[package]
name = "charts-rs"
version = "0.3.7"
authors = ["Tree Xie <tree.xie@outlook.com>"]
edition = "2021"
categories = ["multimedia::images"]
keywords = ["charts", "svg", "plot", "visualization", "graph"]
description = "A charts library for rust"
license = "Apache-2.0"
homepage = "https://github.com/vicanso/charts-rs"
repository = "https://github.com/vicanso/charts-rs"
exclude = ["asset/*", "test/*", "charts-rs-derive/*", "Cargo.lock"]
readme = "./README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charts-rs-derive = { path = "./charts-rs-derive", version = "0.2.1" }
fontdue = "0.8.0"
image = { version = "0.25.1", features = [
    "webp",
    "avif",
    "jpeg",
    "png",
], optional = true }
once_cell = "1.19.0"
regex = "1.10.4"
resvg = { version = "0.41.0", default-features = false, features = [
    "text",
    "system-fonts",
], optional = true }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
snafu = "0.8.2"
substring = "1.4.5"

[features]
image-encoder = ["resvg", "image"]

[dev-dependencies]
criterion = "0.5.1"
pretty_assertions = "1.4.0"

[[bench]]
name = "bench"
harness = false

[package.metadata.docs.rs]
# Whether to pass `--all-features` to Cargo (default: false)
all-features = true
