[package]
name = "charts-rs"
version = "0.1.16"
edition = "2021"
categories = ["multimedia::images"]
keywords = ["charts", "svg", "plot", "visualization", "graph"]
description = "A charts library for rust"
license = "Apache-2.0"
homepage = "https://github.com/vicanso/charts-rs"
repository = "https://github.com/vicanso/charts-rs"
exclude = [
    "asset/*",
    "test/*",
    "charts-rs-derive/*",
    "Cargo.lock"
]
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fontdue = "0.7.3"
once_cell = "1.18.0"
snafu = "0.7.5"
substring = "1.4.5"
charts-rs-derive = { path = "./charts-rs-derive", version = "0.1.4"}
resvg = { version = "0.35.0", default-features = false, features = [ "text", "system-fonts" ], optional = true }
png = { version = "0.17.9", optional = true }
serde = { version = "1.0.175", features = ["derive"] }
serde_json = "1.0.103"
regex = "1.9.1"

[features]
image = ["resvg", "png"]

[dev-dependencies]
criterion = "0.5.1"
pretty_assertions = "1.3.0"

[[bench]]
name = "bench"
harness = false