[package]
name = "charts-rs"
version = "0.3.1"
authors = ["Tree Xie <tree.xie@outlook.com>"]
edition = "2021"
categories = ["multimedia::images"]
keywords = ["charts", "svg", "plot", "visualization", "graph"]
description = "A charts library for rust"
license = "Apache-2.0"
homepage = "https://github.com/vicanso/charts-rs"
repository = "https://github.com/vicanso/charts-rs"
exclude = [
    "asset/*",
    "test/*",
    "charts-rs-derive/*",
    "Cargo.lock"
]
readme = "./README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charts-rs-derive = { path = "./charts-rs-derive", version = "0.1.23" }
fontdue = "0.8.0"
image = { version = "0.24.7", features = ["webp-encoder", "avif-encoder"], optional = true }
once_cell = "1.19.0"
regex = "1.10.2"
resvg = { version = "0.37.0", default-features = false, features = [ "text", "system-fonts" ], optional = true }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
snafu = "0.8.0"
substring = "1.4.5"

[features]
image-encoder = ["resvg", "image"]

[dev-dependencies]
criterion = "0.5.1"
pretty_assertions = "1.4.0"

[[bench]]
name = "bench"
harness = false

[package.metadata.docs.rs]
# Whether to pass `--all-features` to Cargo (default: false)
all-features = true
