[package]
name = "charts-rs"
version = "0.1.0"
edition = "2021"
categories = ["images"]
keywords = ["charts", "svg"]
description = "A charts library for rust"
license = "Apache-2.0"
homepage = "https://github.com/vicanso/charts-rs"
repository = "https://github.com/vicanso/charts-rs"
exclude = [
    "asset/*",
    "test/*",
    "Cargo.lock"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fontdue = "0.7.3"
once_cell = "1.18.0"
snafu = "0.7.4"
substring = "1.4.5"
charts-rs-derive = { path = "./charts-rs-derive", version = "0.1.0"}
resvg = { version = "0.34.1", default-features = false, features = [ "text", "system-fonts" ] }
png = "0.17.9"
serde = { version = "1.0.168", features = ["derive"] }
serde_json = "1.0.100"

[dev-dependencies]
pretty_assertions = "1.3.0"
